/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: ios64-cross"
#define DATE "built on: Wed Dec 18 06:53:10 2024 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','c','c',' ','-','f','P',
    'I','C',' ','-','a','r','c','h',' ','a','r','m','6','4',' ','-',
    'm','i','o','s','-','v','e','r','s','i','o','n','-','m','i','n',
    '=','7','.','0','.','0',' ','-','f','n','o','-','c','o','m','m',
    'o','n',' ','-','i','s','y','s','r','o','o','t',' ','/','A','p',
    'p','l','i','c','a','t','i','o','n','s','/','X','c','o','d','e',
    '.','a','p','p','/','C','o','n','t','e','n','t','s','/','D','e',
    'v','e','l','o','p','e','r','/','P','l','a','t','f','o','r','m',
    's','/','i','P','h','o','n','e','O','S','.','p','l','a','t','f',
    'o','r','m','/','D','e','v','e','l','o','p','e','r','/','S','D',
    'K','s','/','i','P','h','o','n','e','O','S','.','s','d','k',' ',
    '-','O','3',' ','-','D','O','P','E','N','S','S','L','_','P','I',
    'C',' ','-','D','_','R','E','E','N','T','R','A','N','T',' ','-',
    'D','N','D','E','B','U','G','\0'
};
